## 50 câu hỏi ngắn về Numpy

### Câu hỏi 1: import numpy dưới bí danh np và xem phiên bản

In [8]:
import numpy as np
print(np.__version__)

2.3.2


### Câu hỏi 2: Làm thế nào để tạo mảng 1 chiều?

In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

### Câu hỏi 3: Làm thế nào để tạo một mảng boolean?

In [6]:

arr_bool = np.array([True, False, True])

In [68]:
a = np.array([1, 5, 10, 15])

a_bool = a > 5
print(a_bool)


[False False  True  True]


In [72]:
a_bool = np.ones(5, dtype=bool)
print(a_bool)


[ True  True  True  True  True]


In [71]:
a_bool = np.zeros(5, dtype=bool)
print(a_bool)

[False False False False False]


### Câu hỏi 4: Làm thế nào để trích xuất các mục thỏa mãn một điều kiện nhất định từ mảng 1 chiều?
Ví dụ: Trích xuất tất cả các số lẻ từ mảng

In [ ]:

arr = np.array([1, 2, 3, 4, 5])
for i in arr:
    if i % 2 == 1:
        print(i)

1
3
5


### Câu hỏi 5: Làm thế nào để thay thế các mục thỏa mãn một điều kiện bằng một giá trị khác trong mảng numpy?
Ví dụ: Thay thế tất cả các số lẻ trong arr bằng -1

In [ ]:

arr = np.array([1, 2, 3, 4, 5])
for i in range(len(arr)):
    if arr[i] % 2 == 1:
        arr[i] = -1
print(arr)

[-1  2 -1  4 -1]


### Câu hỏi 6: Làm thế nào để thay thế các mục thỏa mãn một điều kiện mà không ảnh hưởng đến mảng ban đầu?
Ví dụ: Thay thế tất cả các số lẻ trong arr bằng -1 mà không thay đổi arr

In [ ]:

arr = np.array([1, 2, 3, 4, 5])
arr_copy = arr.copy()  

for i in range(len(arr)):
    if arr_copy[i] % 2 == 1:
        arr_copy[i] = -1
        
print(arr_copy)
print(arr)

[-1  2 -1  4 -1]
[1 2 3 4 5]


### Câu hỏi 7: Làm thế nào để định hình lại một mảng?

In [16]:
arr_reshape = arr.reshape(5, 1)
print(arr_reshape)

[[1]
 [2]
 [3]
 [4]
 [5]]


### Câu hỏi 8: Làm thế nào để xếp chồng hai mảng theo chiều dọc?

In [20]:
arr2 = np.array([6, 7, 8, 9, 10])

arr_stack = np.vstack((arr, arr2))
print(arr_stack)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### Câu hỏi 9: Làm thế nào để xếp chồng hai mảng theo chiều ngang?

In [21]:
arr_stack_2 = np.hstack((arr, arr2))
print(arr_stack_2)

[ 1  2  3  4  5  6  7  8  9 10]


### Câu hỏi 10: Làm thế nào để tạo các chuỗi tùy chỉnh trong numpy mà không cần mã hóa cứng?
Ví dụ: 
Input: a = np.array([1,2,3])

Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [24]:
a = np.array([1, 2, 3])

temp1 = np.repeat(a, 3)
temp2 = np.tile(a, 3)

array = np.concatenate((temp1, temp2), axis=0)
print(array)


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


### Câu hỏi 11. Làm thế nào để lấy các mục chung giữa hai mảng numpy python?
Ví dụ: 
Input: a = np.array([1,2,3,2,3,4,3,4,5,6])

        b = np.array([7,2,10,2,7,4,9,4,9,8])

Output: array([2, 4])

In [28]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

array = np.intersect1d(a, b)
print(array)

[2 4]


In [36]:
array = np.array([], dtype=int)
for i in a:
    for j in b:
        if i == j and i not in array:
            array = np.append(array, i)            

print(array)


[2 4]


### Câu hỏi 12. Làm thế nào để xóa khỏi một mảng những mục tồn tại trong mảng khác? 
Ví dụ: Input: a = np.array([1,2,3,4,5])

              b = np.array([5,6,7,8,9])

Output: array([1,2,3,4])

In [38]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

array = np.setdiff1d(a, b)
print(array)  

[1 2 3 4]


### Câu hỏi 13. Làm thế nào để lấy các vị trí mà các phần tử của hai mảng khớp nhau?

Ví dụ: 

Input: a = np.array([1,2,3,2,3,4,3,4,5,6])

       b = np.array([7,2,10,2,7,4,9,4,9,8])

Output: (array([1, 3, 5, 7]),)

In [7]:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

vi_tri = np.where(a == b)

print(vi_tri)


(array([1, 3, 5, 7]),)


### Câu hỏi 14. Làm thế nào để trích xuất tất cả các số trong một phạm vi nhất định từ một mảng numpy?

Ví dụ: 
Input: a = np.array([2, 6, 1, 9, 10, 3, 27])

Output: (array([6, 9, 10]),)

In [8]:

a = np.array([2, 6, 1, 9, 10, 3, 27])

temp = a[(a >= 5) & (a <= 10)]

print(temp)


[ 6  9 10]


### Câu hỏi 16. Làm thế nào để hoán đổi hai cột trong một mảng numpy 2 chiều? 

In [9]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a)

a[:, [0, 1]] = a[:, [1, 0]]
print(a)

[[1 2 3]
 [4 5 6]]
[[2 1 3]
 [5 4 6]]


### Câu hỏi 17. Làm thế nào để hoán đổi hai hàng trong một mảng numpy 2 chiều? 

In [10]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a)

a[[0, 1], :] = a[[1, 0], :]
print(a)

[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [1 2 3]]


### Câu hỏi 18. Làm thế nào để đảo ngược các hàng của một mảng 2 chiều? 

In [11]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

a_reverse = a[::-1]
print(a_reverse)

[[4 5 6]
 [1 2 3]]


### Câu hỏi 19. Làm thế nào để đảo ngược các cột của một mảng 2 chiều?

In [12]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

a_reverse = a[:, ::-1]
print(a_reverse)

[[3 2 1]
 [6 5 4]]


### Câu hỏi 20. Làm thế nào để tạo một mảng 2 chiều chứa các số thực ngẫu nhiên giữa 5 và 10?

In [13]:

a = np.random.uniform(5, 10, size=(3, 3))

print(a)


[[7.38075026 6.84368679 8.69633564]
 [7.97452311 7.75537585 7.21273284]
 [8.97295988 7.68347104 5.89106707]]


### Câu hỏi 21. Làm thế nào để chỉ in 3 chữ số thập phân trong mảng numpy python? 

In [16]:
a = np.array([1.12345, 2.434234, 3.98765])

print(a.round(3))

[1.123 2.434 3.988]


### Câu hỏi 22. Làm thế nào để in đẹp một mảng numpy bằng cách loại bỏ ký hiệu khoa học (như 1e10)? 

In [29]:
import numpy as np

a = np.array([1.23e5, 2.34e-8, 4.5678])

np.set_printoptions(formatter={'float_kind': "{:0.4f}".format})
print(a)



[123000.0000 0.0000 4.5678]


### Câu hỏi 24. Làm thế nào để in toàn bộ mảng numpy mà không cần cắt bớt

In [ ]:

a = np.arange(1000)

np.set_printoptions(threshold=np.inf)
print(a)


[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

### Câu hỏi 28. Làm thế nào để tính giá trị trung bình, trung vị, độ lệch chuẩn của một mảng numpy?

In [37]:

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

a_trung_binh = np.mean(a)      
a_trung_vi = np.median(a)   
a_do_lech_chuan = np.std(a)         

print("Gia tri trung binh:", a_trung_binh)
print("Trung vi:", a_trung_vi)
print("Do lech chuan:", a_do_lech_chuan)


Gia tri trung binh: 5.0
Trung vi: 5.0
Do lech chuan: 2.581988897471611


### Câu hỏi 29. Làm thế nào để chuẩn hóa một mảng sao cho các giá trị nằm chính xác trong khoảng từ 0 đến 1?

In [39]:

a = np.array([1, 2, 53, 4, 5])

a_chuan_hoa = (a - a.min()) / (a.max() - a.min())

print(a_chuan_hoa)


[0.    0.019 1.    0.058 0.077]


### Câu hỏi 30. Làm thế nào để tính điểm softmax?

In [40]:

def tinh_softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

a = np.array([1, 2, 3])
print("Softmax:", tinh_softmax(a))



Softmax: [0.09  0.245 0.665]


### Câu hỏi 32. Làm thế nào để chèn các giá trị ở các vị trí ngẫu nhiên trong một mảng?

Ví dụ: Chèn giá trị 0 vào 20 vị trí ngẫu nhiên trong tập dữ liệu a

In [ ]:

a = np.arange(1, 100)   

a_random = np.random.choice(a.size, 20, replace=False)
a[a_random] = 0
print(a_random)
print(a)


[52 61 80 96 18 30 87 39 68 71 37 34 64 13 41 94 45 27 91 35]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13  0 15 16 17 18  0 20 21 22 23 24
 25 26 27  0 29 30  0 32 33 34  0  0 37  0 39  0 41  0 43 44 45  0 47 48
 49 50 51 52  0 54 55 56 57 58 59 60 61  0 63 64  0 66 67 68  0 70 71  0
 73 74 75 76 77 78 79 80  0 82 83 84 85 86 87  0 89 90 91  0 93 94  0 96
  0 98 99]


### Câu hỏi 34. Làm thế nào để lọc một mảng numpy dựa trên hai hoặc nhiều điều kiện?

Ví dụ: Lọc các hàng của a có các giá trị của (cột thứ 3) > 1,5 và các giá trị (cột thứ 1) < 5,0

In [49]:

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

a_loc = (a[:, 2] > 1.5) & (a[:, 0] < 5.0)

for i in range(len(a_loc)):
    if a_loc[i] == True:
        print(a[i, :])


[1 2 3]
[4 5 6]


### Câu hỏi 36. Làm thế nào để tìm mối tương quan giữa hai cột của mảng numpy?

In [51]:

a = np.array([[1, 2],
              [3, 4],
              [5, 6]])

a_tuong_quan = np.corrcoef(a[:, 0], a[:, 1])
print(a_tuong_quan[0, 1])


1.0


### Câu hỏi 44. Làm thế nào để sắp xếp một mảng 2D theo một cột

In [53]:

a = np.array([[1, 6, 3],
              [4, 2, 6],
              [2, 5, 5]])

a_sort = a[a[:, 1].argsort()]

print(a_sort)


[[4 2 6]
 [2 5 5]
 [1 6 3]]


### Câu hỏi 45. Làm thế nào để tìm giá trị thường xuyên nhất trong một mảng numpy?

In [57]:

a = np.array([1, 2, 2, 2, 2, 3, 3, 4])

value, count = np.unique(a, return_counts=True)
print(value)
print(count)

a_so_lan_max = value[np.argmax(count)]
print(np.argmax(count))
print(a_so_lan_max)



[1 2 3 4]
[1 4 2 1]
1
2


### Câu hỏi 47. Làm thế nào để thay thế tất cả các giá trị lớn hơn một giá trị nhất định thành một ngưỡng nhất định?

Ví dụ: Từ mảng a, thay thế tất cả các giá trị lớn hơn 30 đến 30 và nhỏ hơn 10 đến 10.

In [59]:

a = np.array([5, 10, 15, 20, 25, 30, 35])

a[a > 30] = 30

a[a < 10] = 10

print(a)


[10 10 15 20 25 30 30]


### Câu hỏi 48. Làm thế nào để lấy vị trí của n giá trị hàng đầu từ một mảng numpy?

Ví dụ: Lấy vị trí của 5 giá trị lớn nhất trong một mảng cho trước a.

In [64]:

a = np.array([1, 3, 7, 6, 2, 5, 8])
n = 5

a_sort_index = np.argsort(a)
print(a_sort_index)

pos_5_max = a_sort_index[-n:][::-1] 

print("Vi tri cua 5 gia tri lon nhat:", pos_5_max)


[0 4 1 5 3 2 6]
Vi tri cua 5 gia tri lon nhat: [6 2 3 5 1]


### Câu hỏi 50. Làm thế nào để chuyển đổi một mảng các mảng thành một mảng phẳng 1 chiều?

In [ ]:

a = np.array([[1, 2, 3], 
              [4, 5, 6]])

a_1_chieu = a.flatten()
print(a_1_chieu)


[1 2 3 4 5 6]


In [67]:
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

a_1_chieu = a.ravel()
print(a_1_chieu)


[1 2 3 4 5 6]
